### ISSUE TITLE
Crashes in Windows 10 64-bit

### ISSUE THREAD

**Issue by steve-nD** [david-maus/ConanServerManager#1]
Could not find any error logs in the directory nor events in the Event Viewer.

**Comment by david-maus** [comment]
It is crashing on porgramstart?

**Comment by steve-nD** [comment]
It would launch for about 30 seconds and then the dialog would just disappear.  It is also worth noting that BitDefender anti-virus eventually quarantined it and found that it was creating folders/files outside of the designated location.  Is this expected behavior?

**Comment by david-maus** [comment]
The manager is written in python and compiled to an exe through pyinstaller for easiert usage. On execute pyinstaller is creating a tempfolder in the current drives temp directory to execute the python program. So, this is totally normal. Maybe its crashing because your AV is blocking it?

**Comment by david-maus** [comment]
https://github.com/pyinstaller/pyinstaller/issues/680

**Comment by Daniboy41** [comment]
Hey Steve or David does this server tool works as of today Jun 08?

**Comment by BambusRatteTV** [comment]
@david-maus maybe you should use threading, so that gui will not freeze when waiting for cmd closing or anything else, that's the almost problem with windows, because those freezes result in "application is not responding".

**Comment by david-maus** [comment]
The launcher uses threading for mod downloading and checking, the server manager not (i think?). Didnt had the time for updating/reworking the manager... maybe the next weeks. Thanks for feedback
